/**
 * Stores index - exports all Zustand stores
 */

export {
  type AuthState,
  useAccount,
  useAuthError,
  useAuthLoading,
  useAuthStore,
  useIsAuthenticated,
  useRememberMe,
} from './authStore';
export {
  getTranslatedText,
  type MenuState,
  useExtras,
  useFilteredItems,
  useItemsByCategory,
  useMenuCategories,
  useMenuError,
  useMenuItems,
  useMenuLoading,
  useMenuStore,
  useRecentItemIds,
  useRecentItems,
  useSearchQuery,
  useSelectedCategory,
  useSelectedCategoryId,
} from './menuStore';
export {
  type NetworkState,
  selectIsInternetReachable,
  selectIsOffline,
  useNetworkStore,
} from './networkStore';
export {
  type NotificationCall,
  type NotificationPreferences,
  type NotificationState,
  useAcknowledgedCalls,
  useActiveCalls,
  useBadgeCount,
  useCallById,
  useCalls,
  useNotificationActions,
  useNotificationInitialized,
  useNotificationPreferences,
  useNotificationStore,
  usePendingCalls,
  useSoundEnabled,
  useUnreadCount,
  useVibrationEnabled,
} from './notificationStore';
export {
  type MutationType,
  type OfflineQueueState,
  type QueuedMutation,
  type QueueItemStatus,
  useFailedQueueItems,
  useIsQueueInitialized,
  useIsQueueProcessing,
  useLastSyncAt,
  useOfflineQueue,
  useOfflineQueueStore,
  usePendingQueueItems,
  useQueueCounts,
} from './offlineQueueStore';
export {
  // Helper functions
  calculateExtrasTotal,
  calculateItemSubtotal,
  calculateSelectedExtrasTotal,
  clampQuantity,
  convertToOrderItemExtras,
  formatPrice,
  generateLocalId,
  getFormattedPrice,
  // Types
  type LocalOrder,
  type LocalOrderItem,
  // Constants
  MAX_NOTES_LENGTH,
  MAX_QUANTITY,
  MIN_QUANTITY,
  type OrderState,
  parsePrice,
  type SelectedExtra,
  truncateNotes,
  // Store and hooks
  useAvailableExtras,
  useCurrentOrder,
  useMenuItemQuantityInOrder,
  useOrderActions,
  useOrderItems,
  useOrderModified,
  useOrderNotes,
  useOrderStore,
  useOrderTableId,
  useOrderTotals,
} from './orderStore';
export {
  LANGUAGE_NAMES,
  type Language,
  type SettingsState,
  THEME_NAMES,
  type ThemeMode,
  useFloorPlanZoom,
  useLanguage,
  useSettingsActions,
  useSettingsInitialized,
  useSettingsStore,
  useTheme,
  ZOOM_CONSTRAINTS,
} from './settingsStore';
export {
  type TableState,
  type TableViewMode,
  useAssignedTableIds,
  useAssignedTables,
  useIsTableAssigned,
  useSelectedIds,
  useSelectedTable,
  useSelectedZone,
  useTableError,
  useTableLoading,
  useTableStore,
  useTables,
  useTablesByViewMode,
  useTablesInSelectedZone,
  useViewMode,
  useViewModeToggle,
  useZones,
} from './tableStore';
